// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_Initialize
void cpp_Initialize(NumericMatrix features, NumericVector x, IntegerVector delta1, IntegerVector delta2, double h);
RcppExport SEXP _cmpp_cpp_Initialize(SEXP featuresSEXP, SEXP xSEXP, SEXP delta1SEXP, SEXP delta2SEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta2(delta2SEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    cpp_Initialize(features, x, delta1, delta2, h);
    return R_NilValue;
END_RCPP
}
// cpp_cdf_gomp
double cpp_cdf_gomp(double time, double shape, double scale);
RcppExport SEXP _cmpp_cpp_cdf_gomp(SEXP timeSEXP, SEXP shapeSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cdf_gomp(time, shape, scale));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pdf_gomp
double cpp_pdf_gomp(double x, double alpha, double beta);
RcppExport SEXP _cmpp_cpp_pdf_gomp(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pdf_gomp(x, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// cpp_GetDim
Rcpp::List cpp_GetDim();
RcppExport SEXP _cmpp_cpp_GetDim() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_GetDim());
    return rcpp_result_gen;
END_RCPP
}
// cpp_LogLike1
SEXP cpp_LogLike1(SEXP paramSEXP);
RcppExport SEXP _cmpp_cpp_LogLike1(SEXP paramSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramSEXP(paramSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_LogLike1(paramSEXP));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_grad
SEXP cpp_compute_grad(SEXP paramSEXP);
RcppExport SEXP _cmpp_cpp_compute_grad(SEXP paramSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramSEXP(paramSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_grad(paramSEXP));
    return rcpp_result_gen;
END_RCPP
}
// cpp_makeMat
Eigen::MatrixXd cpp_makeMat(int n, int m, double value);
RcppExport SEXP _cmpp_cpp_makeMat(SEXP nSEXP, SEXP mSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_makeMat(n, m, value));
    return rcpp_result_gen;
END_RCPP
}
// cpp_Cleanup
void cpp_Cleanup();
RcppExport SEXP _cmpp_cpp_Cleanup() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_Cleanup();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cmpp_cpp_Initialize", (DL_FUNC) &_cmpp_cpp_Initialize, 5},
    {"_cmpp_cpp_cdf_gomp", (DL_FUNC) &_cmpp_cpp_cdf_gomp, 3},
    {"_cmpp_cpp_pdf_gomp", (DL_FUNC) &_cmpp_cpp_pdf_gomp, 3},
    {"_cmpp_cpp_GetDim", (DL_FUNC) &_cmpp_cpp_GetDim, 0},
    {"_cmpp_cpp_LogLike1", (DL_FUNC) &_cmpp_cpp_LogLike1, 1},
    {"_cmpp_cpp_compute_grad", (DL_FUNC) &_cmpp_cpp_compute_grad, 1},
    {"_cmpp_cpp_makeMat", (DL_FUNC) &_cmpp_cpp_makeMat, 3},
    {"_cmpp_cpp_Cleanup", (DL_FUNC) &_cmpp_cpp_Cleanup, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_cmpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
