// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Initialize
void Initialize(NumericMatrix features, NumericVector x, IntegerVector delta1, IntegerVector delta2, double h);
RcppExport SEXP _cmpp_Initialize(SEXP featuresSEXP, SEXP xSEXP, SEXP delta1SEXP, SEXP delta2SEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta2(delta2SEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Initialize(features, x, delta1, delta2, h);
    return R_NilValue;
END_RCPP
}
// cdf_gomp
double cdf_gomp(double x, double alpha, double beta);
RcppExport SEXP _cmpp_cdf_gomp(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(cdf_gomp(x, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// pdf_gomp
double pdf_gomp(double x, double alpha, double beta);
RcppExport SEXP _cmpp_pdf_gomp(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(pdf_gomp(x, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// GetDim
Rcpp::List GetDim();
RcppExport SEXP _cmpp_GetDim() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(GetDim());
    return rcpp_result_gen;
END_RCPP
}
// LogLike1
double LogLike1(Eigen::VectorXd& Param);
RcppExport SEXP _cmpp_LogLike1(SEXP ParamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type Param(ParamSEXP);
    rcpp_result_gen = Rcpp::wrap(LogLike1(Param));
    return rcpp_result_gen;
END_RCPP
}
// GrLike
double GrLike(const Eigen::VectorXd& Param, Eigen::VectorXd& grad);
RcppExport SEXP _cmpp_GrLike(SEXP ParamSEXP, SEXP gradSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Param(ParamSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type grad(gradSEXP);
    rcpp_result_gen = Rcpp::wrap(GrLike(Param, grad));
    return rcpp_result_gen;
END_RCPP
}
// compute_grad
Eigen::VectorXd compute_grad(const Eigen::VectorXd& Param);
RcppExport SEXP _cmpp_compute_grad(SEXP ParamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Param(ParamSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_grad(Param));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP cdf_gomp(SEXP, SEXP, SEXP);
RcppExport SEXP compute_grad(SEXP);
RcppExport SEXP GrLike(SEXP);
RcppExport SEXP Initialize(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP LogLike1(SEXP);
RcppExport SEXP pdf_gomp(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_cmpp_Initialize", (DL_FUNC) &_cmpp_Initialize, 5},
    {"_cmpp_cdf_gomp", (DL_FUNC) &_cmpp_cdf_gomp, 3},
    {"_cmpp_pdf_gomp", (DL_FUNC) &_cmpp_pdf_gomp, 3},
    {"_cmpp_GetDim", (DL_FUNC) &_cmpp_GetDim, 0},
    {"_cmpp_LogLike1", (DL_FUNC) &_cmpp_LogLike1, 1},
    {"_cmpp_GrLike", (DL_FUNC) &_cmpp_GrLike, 2},
    {"_cmpp_compute_grad", (DL_FUNC) &_cmpp_compute_grad, 1},
    {"cdf_gomp",     (DL_FUNC) &cdf_gomp,     3},
    {"compute_grad", (DL_FUNC) &compute_grad, 1},
    {"GrLike",       (DL_FUNC) &GrLike,       1},
    {"Initialize",   (DL_FUNC) &Initialize,   5},
    {"LogLike1",     (DL_FUNC) &LogLike1,     1},
    {"pdf_gomp",     (DL_FUNC) &pdf_gomp,     3},
    {NULL, NULL, 0}
};

RcppExport void R_init_cmpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
