# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Initialize <- function(features, x, delta1, delta2, h) {
    invisible(.Call(`_cmpp_Initialize`, features, x, delta1, delta2, h))
}

cdf_gomp <- function(x, alpha, beta) {
    .Call(`_cmpp_cdf_gomp`, x, alpha, beta)
}

pdf_gomp <- function(x, alpha, beta) {
    .Call(`_cmpp_pdf_gomp`, x, alpha, beta)
}

GetDim <- function() {
    .Call(`_cmpp_GetDim`)
}

LogLike1 <- function(Param) {
    .Call(`_cmpp_LogLike1`, Param)
}

GrLike <- function(Param, grad) {
    .Call(`_cmpp_GrLike`, Param, grad)
}

compute_grad <- function(Param) {
    .Call(`_cmpp_compute_grad`, Param)
}

