# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Initialize <- function(features, x, delta1, delta2, h) {
    invisible(.Call(`_cmpp_Initialize`, features, x, delta1, delta2, h))
}

cdf_gomp <- function(x, alpha, beta) {
    .Call(`_cmpp_cdf_gomp`, x, alpha, beta)
}

pdf_gomp <- function(x, alpha, beta) {
    .Call(`_cmpp_pdf_gomp`, x, alpha, beta)
}

GetDim <- function() {
    .Call(`_cmpp_GetDim`)
}

LogLike1 <- function(param) {
    .Call(`_cmpp_LogLike1`, param)
}

compute_grad <- function(param) {
    .Call(`_cmpp_compute_grad`, param)
}

compute_hessian <- function(param) {
    .Call(`_cmpp_compute_hessian`, param)
}

makeMat <- function(n, m, value) {
    .Call(`_cmpp_makeMat`, n, m, value)
}

Cleanup <- function() {
    invisible(.Call(`_cmpp_Cleanup`))
}

bootstrap_variance <- function(features, x, delta1, delta2, initial_params, n_bootstrap, optimMethod) {
    .Call(`_cmpp_bootstrap_variance`, features, x, delta1, delta2, initial_params, n_bootstrap, optimMethod)
}

F_cdf_rcpp <- function(Params, Z, x) {
    .Call(`_cmpp_F_cdf_rcpp`, Params, Z, x)
}

f_pdf_rcpp <- function(Params, Z, x) {
    .Call(`_cmpp_f_pdf_rcpp`, Params, Z, x)
}

log_f_rcpp <- function(Params) {
    .Call(`_cmpp_log_f_rcpp`, Params)
}

compute_log_f_gradient_rcpp <- function(Params) {
    .Call(`_cmpp_compute_log_f_gradient_rcpp`, Params)
}

compute_log_f_hessian_rcpp <- function(Params) {
    .Call(`_cmpp_compute_log_f_hessian_rcpp`, Params)
}

F_cdf_rcpp2 <- function(Params, Z, x) {
    .Call(`_cmpp_F_cdf_rcpp2`, Params, Z, x)
}

f_pdf_rcpp2 <- function(Params, Z, x) {
    .Call(`_cmpp_f_pdf_rcpp2`, Params, Z, x)
}

log_f_rcpp2 <- function(Params) {
    .Call(`_cmpp_log_f_rcpp2`, Params)
}

compute_log_f_gradient_rcpp2 <- function(Params) {
    .Call(`_cmpp_compute_log_f_gradient_rcpp2`, Params)
}

F_cdf_rcpp3 <- function(Params, Z, x) {
    .Call(`_cmpp_F_cdf_rcpp3`, Params, Z, x)
}

f_pdf_rcpp3 <- function(Params, Z, x) {
    .Call(`_cmpp_f_pdf_rcpp3`, Params, Z, x)
}

log_f_rcpp3 <- function(Params) {
    .Call(`_cmpp_log_f_rcpp3`, Params)
}

compute_log_f_gradient_rcpp3 <- function(Params) {
    .Call(`_cmpp_compute_log_f_gradient_rcpp3`, Params)
}

GetData <- function() {
    .Call(`_cmpp_GetData`)
}

